sudo: required
language: bash
services:
- docker
env:
  global:
    secure: TXB2uD2XR3l05/7ywb6p49frt/JaDSu6/4rLnbpelzmo7owkWcr9cZUIjOy6WNaJEwxyGYxWFsndSkIXNhpULOULfXZ52hYhRsA4NtWDqeqcGN/l3jyk0zT6jG7nhHR018WyoKhjkM897ugicfM1ES84P4v9OlCvg/h5OS7PC6WFjWNu+fRiaGRF1zx+953Z1957krPU/zb/gbAdyzHu+5YbYIbOzoRdHgAD1Q0hP7GcmYzGE2O9CUAufPbawNG/40oIV9eZgh5o+DspcdDQI8ccDtIslur525wv2V/JxqdwIEwNUii9OYCCTIvw7b0dHk7Nzmr3XIUnXIp0F+4RzlH3/O3UjjHDnqXRH1MbyOtzD4IvTj4v6f4VfsQBVnLp6gegHKJyMFccpo4u162dUs7dPw8pV+qR8pPQnPvghDl0SezMFbQTUdT72anaWi3ag31NyDxH2k9WcbLvtMH+XAyAe42cXJ/EaJNokUSJmTne5mDFhYMl5LPdRts42uR3eIFEbmHr0F+y+F513Z9bduG//2tehOmhm28Errf5Q5iYd3aJfF88ucn9dGQvwHDXbECXxAUwpFkeogboZPljsXzCAbtgjp0c3xYIdYybBJKEZht46Aqa59Jhs53lyPbXswL5lNK4Jqw7nPQe3mK7TFZouCbKNHZq4ch0qJjv4xw=

  matrix:
  - ARCH=amd64 GOARCH=amd64 GOARM=6 QQEMU_ARCH=x86_64 TAG=amd64
  - ARCH=armhf GOARCH=arm   GOARM=6 QEMU_ARCH=arm     TAG=arm
  - ARCH=arm64 GOARCH=arm64 GOARM=6 QEMU_ARCH=arm64   TAG=arm64
before_install:
- curl -L https://goss.rocks/install | sudo sh
- sudo apt-get -y install qemu-user-static
- docker run --rm --privileged multiarch/qemu-user-static:register
script:
- docker build -t mdavis332/cloudflared:$TAG --build-arg ARCH="$ARCH" --build-arg
  GOARCH="$GOARCH" --build-arg GOARM="$GOARM" ./
- dgoss run --name cloudflared -ti mdavis332/cloudflared:$TAG
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then docker login -u=mdavis332 -p="$DOCKER_PASSWORD";
  docker push mdavis332/cloudflared:$TAG; fi
